var adjectives = [
"agile",
"responsive",
"social",
"mobile-first",
"lean",
"Web 3.0",
"user-driven",
"native",
"test-driven",
"device-agnostic",
"flexible",
"dependency-free",
"baked-in",
"lightweight",
"modular",
"bootstrapped"];

var companies = [
"SnapChat",
"Instagram",
"Twitter",
"MySpace",
"YouTube",
"online-dating service",
"T-shirt store",
"online-banking service",
"Reddit",
"Yelp",
"Tumblr",
"Spotify",
"Netflix",
"Skype",
"Ebay",
"Vine",
"Pinterest",
"Angry Birds",
"Soundcloud",
"DropBox",
"Craiglist",
"LinkedIn",
"Facebook",
"GitHub"];

var endings = [
" with a flat UI",
" in the cloud",
" with upvotes",
" as a service",
" which runs anywhere",
" built with the users in mind",
" focused on UX",
" promoted through viral marketing",
" that will disrupt the entire industry",
" completely crowd-sourced",
" funded through Kickstarter"];